/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CodeDeployerFactoryInterface extends Interface {
  getFunction(nameOrSignature: "deploy"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CodeDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "deploy",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
}

export namespace CodeDeployedEvent {
  export type InputTuple = [destination: AddressLike];
  export type OutputTuple = [destination: string];
  export interface OutputObject {
    destination: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CodeDeployerFactory extends BaseContract {
  connect(runner?: ContractRunner | null): CodeDeployerFactory;
  waitForDeployment(): Promise<this>;

  interface: CodeDeployerFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deploy: TypedContractMethod<
    [data: BytesLike, preventExecution: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deploy"
  ): TypedContractMethod<
    [data: BytesLike, preventExecution: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CodeDeployed"
  ): TypedContractEvent<
    CodeDeployedEvent.InputTuple,
    CodeDeployedEvent.OutputTuple,
    CodeDeployedEvent.OutputObject
  >;

  filters: {
    "CodeDeployed(address)": TypedContractEvent<
      CodeDeployedEvent.InputTuple,
      CodeDeployedEvent.OutputTuple,
      CodeDeployedEvent.OutputObject
    >;
    CodeDeployed: TypedContractEvent<
      CodeDeployedEvent.InputTuple,
      CodeDeployedEvent.OutputTuple,
      CodeDeployedEvent.OutputObject
    >;
  };
}
